insert into public.productos (nombre, descripcion, precio, imagen) values
('Smartphone Galaxy A54', 'Teléfono inteligente de gama media con pantalla Super AMOLED de 120Hz, 8GB RAM y 256GB de almacenamiento.', 7499,
'https://image.pollinations.ai/prompt/Samsung%20Galaxy%20A54%20on%20white%20background'),
('Laptop ASUS ZenBook', 'Ultrabook ligera con procesador Ryzen 7, pantalla OLED y chasis de aluminio cepillado.', 18999,
'https://image.pollinations.ai/prompt/ASUS%20ZenBook%20laptop%20on%20white%20background'),
('Audífonos Sony WH-1000XM5', 'Auriculares inalámbricos con cancelación activa de ruido y batería de larga duración.', 5899,
'https://image.pollinations.ai/prompt/Sony%20WH-1000XM5%20headphones%20studio%20photo'),
('Cafetera Nespresso Vertuo', 'Cafetera de cápsulas con tecnología de extracción centrífuga y depósito de agua de 1.2L.', 4199,
'https://image.pollinations.ai/prompt/Nespresso%20Vertuo%20coffee%20machine%20on%20kitchen%20counter'),
('Silla ergonómica Secretlab Titan Evo', 'Silla ergonómica con soporte lumbar ajustable y tapizado de cuero sintético.', 11299,
'https://image.pollinations.ai/prompt/Secretlab%20Titan%20Evo%20ergonomic%20chair%20office%20studio'),
('Reloj inteligente Garmin Venu 2', 'Reloj deportivo con GPS integrado, oxímetro y métricas de salud avanzadas.', 8299,
'https://image.pollinations.ai/prompt/Garmin%20Venu%202%20smartwatch%20on%20white%20background'),
('Cámara Canon EOS R50', 'Cámara mirrorless APS-C con sensor de 24MP y lente 18-45mm f/4.5-6.3 IS STM.', 19999,
'https://image.pollinations.ai/prompt/Canon%20EOS%20R50%20mirrorless%20camera%20product%20photo'),
('Teclado mecánico Keychron K8', 'Teclado mecánico inalámbrico con retroiluminación RGB y switches hot-swappable.', 2499,
'https://image.pollinations.ai/prompt/Keychron%20K8%20mechanical%20keyboard%20RGB'),
('Monitor LG UltraGear 27GL83A', 'Monitor gamer de 27” QHD con panel IPS y tasa de refresco de 144Hz.', 7399,
'https://image.pollinations.ai/prompt/LG%20UltraGear%2027-inch%20gaming%20monitor'),
('Mochila North Face Borealis', 'Mochila resistente al agua de 28L con compartimiento acolchado para laptop.', 2899,
'https://image.pollinations.ai/prompt/The%20North%20Face%20Borealis%20backpack%20outdoor%20studio'),
('Cámara de seguridad TP-Link Tapo C210', 'Cámara WiFi 2K con visión nocturna y detección de movimiento.', 999,
'https://image.pollinations.ai/prompt/TP-Link%20Tapo%20C210%20security%20camera%20on%20white%20background'),
('Mouse Logitech MX Master 3S', 'Mouse ergonómico inalámbrico con sensor de alta precisión y scroll electromagnético.', 1899,
'https://image.pollinations.ai/prompt/Logitech%20MX%20Master%203S%20mouse%20product%20photo'),
('Televisor Samsung QLED 55”', 'Smart TV 4K con tecnología Quantum Dot y compatibilidad HDR10+.', 12999,
'https://image.pollinations.ai/prompt/Samsung%20QLED%2055-inch%20TV%20living%20room'),
('Aspiradora Dyson V12 Detect Slim', 'Aspiradora inalámbrica con detección láser de polvo y potencia ciclónica.', 15999,
'https://image.pollinations.ai/prompt/Dyson%20V12%20Detect%20Slim%20vacuum%20cleaner%20product%20photo'),
('Consola Nintendo Switch OLED', 'Consola híbrida con pantalla OLED de 7” y Joy-Con mejorados.', 8499,
'https://image.pollinations.ai/prompt/Nintendo%20Switch%20OLED%20console%20on%20white%20background');

insert into public.productos (nombre, descripcion, precio, imagen) values
('Playera básica Uniqlo Supima Cotton', 'Playera de algodón Supima con corte regular y tacto ultra suave.', 399,
'https://image.pollinations.ai/prompt/Uniqlo%20Supima%20Cotton%20t-shirt%20folded%20on%20white%20background'),
('Tenis Nike Air Max 270', 'Tenis deportivos con cámara de aire visible y amortiguación premium.', 2899,
'https://image.pollinations.ai/prompt/Nike%20Air%20Max%20270%20sneakers%20studio%20photo'),
('Pantalón Levi’s 511 Slim Fit', 'Jeans de corte ajustado con mezclilla elástica de alta durabilidad.', 1499,
'https://image.pollinations.ai/prompt/Levis%20511%20Slim%20Fit%20jeans%20denim%20on%20white%20background'),
('Sudadera Adidas Essentials', 'Sudadera con capucha y bolsillo tipo canguro, elaborada en felpa suave.', 899,
'https://image.pollinations.ai/prompt/Adidas%20Essentials%20hoodie%20gray%20on%20hanger'),
('Mochila Fjällräven Kånken Classic', 'Mochila icónica de diseño sueco con material vinylon resistente al agua.', 2399,
'https://image.pollinations.ai/prompt/Fjallraven%20Kanken%20Classic%20backpack%20studio%20photo'),
('Set de plumones Tombow Dual Brush', 'Set de 10 plumones de doble punta, ideal para lettering y dibujo artístico.', 749,
'https://image.pollinations.ai/prompt/Tombow%20Dual%20Brush%20pen%20set%20art%20supplies'),
('Libreta Moleskine Classic', 'Libreta tamaño A5 con cubierta dura, hojas rayadas y cinta separadora.', 459,
'https://image.pollinations.ai/prompt/Moleskine%20Classic%20notebook%20on%20desk'),
('Lápiz mecánico Pentel GraphGear 1000', 'Lápiz metálico de ingeniería con grip ergonómico y sistema retráctil.', 399,
'https://image.pollinations.ai/prompt/Pentel%20GraphGear%201000%20mechanical%20pencil%20product%20photo'),
('Cafetera italiana Bialetti Moka Express', 'Cafetera clásica de aluminio de 6 tazas con válvula de seguridad.', 899,
'https://image.pollinations.ai/prompt/Bialetti%20Moka%20Express%20coffee%20maker%20studio%20photo'),
('Juego de cuchillos Victorinox Swiss Classic', 'Set de 6 cuchillos con filo de acero inoxidable y mangos ergonómicos.', 1299,
'https://image.pollinations.ai/prompt/Victorinox%20Swiss%20Classic%20knife%20set%20kitchen%20product'),
('Sartén T-fal Expertise 28cm', 'Sartén antiadherente con tecnología Thermo-Spot y mango ergonómico.', 749,
'https://image.pollinations.ai/prompt/T-fal%20Expertise%20frying%20pan%20product%20photo'),
('Set de tazas de cerámica artesanal', 'Juego de 4 tazas pintadas a mano con esmalte brillante.', 599,
'https://image.pollinations.ai/prompt/handmade%20ceramic%20coffee%20mugs%20set%20studio%20photo'),
('Difusor de aromas con luz LED', 'Difusor ultrasónico de aceites esenciales con iluminación ambiental.', 699,
'https://image.pollinations.ai/prompt/aromatherapy%20diffuser%20LED%20humidifier%20minimalist'),
('Cojín decorativo de lino', 'Cojín cuadrado de 45x45 cm con funda lavable y relleno suave.', 349,
'https://image.pollinations.ai/prompt/decorative%20linen%20pillow%20sofa%20product%20photo'),
('Planta artificial Monstera', 'Planta decorativa de Monstera deliciosa con maceta de cerámica blanca.', 799,
'https://image.pollinations.ai/prompt/artificial%20monstera%20plant%20in%20white%20pot'),
('Croquetas Royal Canin Medium Adult 15kg', 'Alimento balanceado para perros adultos medianos.', 1999,
'https://image.pollinations.ai/prompt/Royal%20Canin%20Medium%20Adult%20dog%20food%20bag'),
('Arena para gato Tidy Cats Lightweight', 'Arena aglutinante con control de olor y peso reducido.', 479,
'https://image.pollinations.ai/prompt/Tidy%20Cats%20Lightweight%20cat%20litter%20product%20photo'),
('Juguete para gato con plumas', 'Juguete interactivo con varita, cuerda y plumas naturales.', 129,
'https://image.pollinations.ai/prompt/cat%20feather%20toy%20on%20white%20background'),
('Chocolate artesanal mexicano 70% cacao', 'Tableta de chocolate oscuro artesanal con cacao orgánico de Chiapas.', 129,
'https://image.pollinations.ai/prompt/mexican%20artisanal%20dark%20chocolate%20bar%20studio%20photo'),
('Café de especialidad Veracruz', 'Café arábica molido, tueste medio, con notas a caramelo y almendra.', 239,
'https://image.pollinations.ai/prompt/Veracruz%20specialty%20coffee%20beans%20on%20table');

insert into public.productos (nombre, descripcion, precio, imagen) values
('Cargador inalámbrico Anker PowerWave', 'Base de carga rápida Qi compatible con iPhone y Android, diseño antideslizante.', 699,
'https://image.pollinations.ai/prompt/Anker%20PowerWave%20wireless%20charger%20on%20white%20background'),
('Lámpara de escritorio LED Xiaomi Mi Smart', 'Lámpara LED con control de brillo y temperatura de color ajustable por app.', 1199,
'https://image.pollinations.ai/prompt/Xiaomi%20Mi%20Smart%20LED%20desk%20lamp%20minimalist%20photo'),
('Bocina Bluetooth JBL Go 3', 'Bocina portátil resistente al agua con sonido potente y diseño compacto.', 899,
'https://image.pollinations.ai/prompt/JBL%20Go%203%20bluetooth%20speaker%20product%20photo'),
('Banco de energía Aukey 20000mAh', 'Power bank con carga rápida de 18W y doble puerto USB-C.', 999,
'https://image.pollinations.ai/prompt/Aukey%2020000mAh%20power%20bank%20on%20white%20background'),
('Mini proyector portátil ViewSonic M1', 'Proyector LED con batería integrada y altavoces Harman Kardon.', 6999,
'https://image.pollinations.ai/prompt/ViewSonic%20M1%20mini%20projector%20home%20theater%20photo'),
('Teclado numérico Bluetooth Satechi', 'Teclado numérico inalámbrico de aluminio con batería recargable USB-C.', 899,
'https://image.pollinations.ai/prompt/Satechi%20Bluetooth%20numeric%20keypad%20aluminum'),
('Organizador de escritorio de bambú', 'Organizador multifuncional con compartimentos para papelería y gadgets.', 499,
'https://image.pollinations.ai/prompt/bamboo%20desk%20organizer%20office%20setup'),
('Reloj despertador digital con proyección', 'Despertador con pantalla LED, proyección de hora en pared y alarma dual.', 849,
'https://image.pollinations.ai/prompt/digital%20projection%20alarm%20clock%20modern%20photo'),
('Soporte ergonómico para laptop', 'Soporte ajustable de aluminio que mejora la postura y ventilación del equipo.', 649,
'https://image.pollinations.ai/prompt/aluminum%20laptop%20stand%20ergonomic%20on%20white%20background'),
('Llavero multiherramienta KeySmart', 'Llavero compacto con navaja, destapador y destornillador integrados.', 399,
'https://image.pollinations.ai/prompt/KeySmart%20multitool%20keychain%20studio%20photo'),
('Mini dron DJI Tello', 'Dron compacto con cámara HD y control por smartphone, ideal para principiantes.', 3499,
'https://image.pollinations.ai/prompt/DJI%20Tello%20mini%20drone%20on%20white%20background'),
('Cámara instantánea Fujifilm Instax Mini 12', 'Cámara instantánea de película con flash automático y diseño colorido.', 2599,
'https://image.pollinations.ai/prompt/Fujifilm%20Instax%20Mini%2012%20instant%20camera%20pastel%20colors'),
('Auriculares inalámbricos Redmi Buds 4', 'Audífonos Bluetooth con cancelación de ruido y estuche de carga.', 899,
'https://image.pollinations.ai/prompt/Redmi%20Buds%204%20wireless%20earbuds%20on%20white%20background'),
('Pulsera de actividad Xiaomi Smart Band 8', 'Pulsera fitness con pantalla AMOLED y seguimiento de salud 24/7.', 999,
'https://image.pollinations.ai/prompt/Xiaomi%20Smart%20Band%208%20fitness%20tracker%20photo'),
('Soporte magnético para celular Baseus', 'Soporte para automóvil con sujeción magnética y rotación de 360°.', 299,
'https://image.pollinations.ai/prompt/Baseus%20magnetic%20car%20mount%20holder%20studio%20photo'),
('Difusor USB con luces RGB', 'Difusor portátil de aromaterapia con iluminación ambiental de colores.', 449,
'https://image.pollinations.ai/prompt/USB%20aroma%20diffuser%20RGB%20lights%20minimalist%20photo'),
('Set de velas aromáticas', 'Paquete de 3 velas con fragancias de lavanda, vainilla y sándalo.', 549,
'https://image.pollinations.ai/prompt/aromatic%20scented%20candle%20set%20aesthetic%20photo'),
('Cartera minimalista RFID Secrid', 'Cartera de aluminio con protección RFID y mecanismo de extracción rápida.', 1499,
'https://image.pollinations.ai/prompt/Secrid%20RFID%20wallet%20aluminum%20product%20photo'),
('Botella térmica Stanley Classic 1L', 'Botella de acero inoxidable con aislamiento térmico de doble pared.', 999,
'https://image.pollinations.ai/prompt/Stanley%20Classic%20thermal%20bottle%20green%20product%20photo'),
('Mini altavoz con luz ambiental', 'Bocina portátil Bluetooth con iluminación LED cálida y batería recargable.', 699,
'https://image.pollinations.ai/prompt/mini%20Bluetooth%20speaker%20with%20ambient%20light%20modern%20photo');